openapi: 3.0.0
info:
  title: Video Compression API
  description: |
    API for uploading, compressing, and downloading videos. 
    This documentation provides detailed setup instructions and examples.
  version: 1.0.0
  contact:
    name: Abhishek Shah
    email: abhishekshah03737@gmail.com
    url: https://www.linkedin.com/in/abhishek-shah007

servers:
  - url: http://localhost:5000
    description: Local Development Server

paths:
  /videos/upload:
    post:
      summary: Upload and Compress a Video
      description: Upload a video to the server, compress it, and store both the original and compressed video URLs.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                video:
                  type: string
                  format: binary
                  description: The video file to be uploaded.
      responses:
        '200':
          description: Video uploaded and compressed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  video:
                    type: object
                    properties:
                      originalFileName:
                        type: string
                        description: The original name of the uploaded video file.
                      originalUrl:
                        type: string
                        description: URL of the original video.
                      compressedFileName:
                        type: string
                        description: The name of the compressed video file.
                      compressedUrl:
                        type: string
                        description: URL of the compressed video.
                  originalFileSize:
                    type: integer
                    description: Size of the original file in bytes.
                  compressedFileSize:
                    type: integer
                    description: Size of the compressed file in bytes.
        '400':
          description: Bad Request. No file was uploaded.
        '500':
          description: Internal Server Error. Video compression or upload failed.

  /videos/{id}/download:
    get:
      summary: Download Compressed Video
      description: Fetch the compressed video by its unique ID and redirect to its URL.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The unique ID of the video.
      responses:
        '302':
          description: Redirect to the compressed video URL.
        '404':
          description: Video not found.
        '500':
          description: Internal Server Error.

components:
  schemas:
    Video:
      type: object
      properties:
        _id:
          type: string
          description: Unique identifier for the video.
        originalFileName:
          type: string
          description: The original name of the uploaded video file.
        originalUrl:
          type: string
          description: URL of the original video.
        compressedFileName:
          type: string
          description: The name of the compressed video file.
        compressedUrl:
          type: string
          description: URL of the compressed video.
        originalFileSize:
          type: integer
          description: Size of the original file in bytes.
        compressedFileSize:
          type: integer
          description: Size of the compressed file in bytes.
  responses:
    NotFound:
      description: The requested resource was not found.
    InternalServerError:
      description: Internal server error.

tags:
  - name: Video
    description: Operations related to video upload, compression, and download.

